trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x' # Use Python 3.x
    addToPath: true

- script: |
    pip install --upgrade pip
    pip install language-tool-python
  displayName: 'Install LanguageTool'

- script: |
    lt --version
    lt --json /path/to/your/code
  displayName: 'Check Grammar'
